export const INITIALIZE = "INITIALIZE";

export const SERVER_ADD = "SERVER_ADD";
export const SERVER_REMOVE = "SERVER_REMOVE";
export const SERVER_EDIT = "SERVER_EDIT";
export const SERVER_POLL = "SERVER_POLL";
export const SERVER_POLL_SUCCESS = "SERVER_POLL_SUCCESS";
export const SERVER_POLL_FAILURE = "SERVER_POLL_FAILURE";

export const VIEW_CHANGE = "VIEW_CHANGE";

export const STATE_LOAD = "STATE_LOAD";
export const STATE_SAVE = "STATE_SAVE";

export const UPDATE_LAST_UPDATED = "UPDATE_LAST_UPDATED";
