#!/usr/bin/env node

var program = require('commander');

program
	.option('-c, --config <config>', 'path to config')
	.option('-p, --port <port>', 'port number')
	.parse(process.argv);

require("../src/server.js")(program.port, program.config);